HAPPY_WORDS = ["laughter", "happiness", "love", "happy", "laughed", "laugh", 
"laughing", "laughs", "excellent", "successful", "joy", "win", "rainbow", 
"smile", "won", "smiled", "pleasure", "rainbows", "winning", "celebration", 
"enjoyed", "healthy", "music", "celebrating", "congratulations", "weekend", 
"jokes", "victory", "rich", "celebrate", "comedy", "friendship", "holidays", 
"loving", "loves", "loved", "christmas", "fun", "free", "kissing", "sunshine",
 "beach", "hahaha", "sweetest", "butterflies", "outstanding", "paradise", 
 "delicious", "vacation", "funny", "beautiful", "friends", "freedom", 
 "sunlight", "sweetness", "sweetheart", "flower", "great", "splendid", 
 "award", "hahahaha", "heaven", "peace", "success", "chocolate", "kissed",
 "enjoying", "attraction", "celebrated", "hugs", "hero", "positive", "sun",
 "delight", "winner", "blessed", "fantastic", "birthday", "succeed",
 "honesty", "butterfly", "funniest", "smiles", "entertainment", "beauty",
 "sky", "wonderful", "glorious", "promotion", "kisses", "romantic", "humor",
 "gift", "family", "honour", "weekends", "cupcakes", "hahahahaha",
 "festival", "relax", "b-day", "diamonds", "bonus", "brilliant", "angel",
 "mother", "lucky", "holiday", "super", "mother's", "finest", "angels",
 "profit", "friendly", "enjoy", "amazing", "friend", "grandmother",
 "kitten", "champion", "miracle", "bday", "kiss", "sweet", "mom", "haha",
 "succeeded", "successfully", "cutest", "blessings", "entertaining", 
 "winners", "millionaire", "excitement", "prize", "bright", "joke", "excited",
 "shines", "genius", "awesome", "succeeding", "victories", "smiling", "tasty",
 "income", "achievement", "cheers", "goodness", "puppy", "exciting", "hug",
 "cake", "party", "song", "achieved", "cakes", "flowers", "billion", "easier",
 "gifts", "gold", "merry", "lovers", "families", "handsome", "affection",
 "earnings", "peacefully", "saturdays", "roses", "praise", "diamond",
 "relaxing", "candy", "interesting", "cute", "faithful", "heavens",
 "extraordinary", "cherish", "cupcake", "moonlight", "optimistic", "peaceful",
 "romance", "glory", "comfort", "earn", "hilarious", "congrats", "feast",
 "pleasant", "profits", "x-mas", "attractive", "grandma", "smart", "internet",
 "glad", "enthusiasm"]

SAD_WORDS = ["terrorist", "suicide", "rape", "terrorism", "murder", "cancer",
 "death", "died", "killed", "kill", "torture", "deaths", "raped", "arrested",
 "killing", "die", "terror", "jail", "kills", "fatal", "killings", "murdered",
 "war", "tortured", "abused", "sickness", "cruel", "failed", "cry", "violence",
 "diseases", "sadness", "abuse", "depressing", "earthquake", "wars", "evil",
 "poison", "disaster", "bomb", "fail", "poverty", "tumors", "depression",
 "criminal", "headache", "illness", "punishment", "killers", "disease", "dead",
 "slavery", "rejection", "motherfucker", "sick", "destroyed", "injury",
 "crying", "slaves", "bankruptcy", "tragedy", "slave", "fails", "violent",
 "prison", "hates", "failure", "rejected", "robbery", "suffer", "racist",
 "virus", "dies", "funeral", "dying", "worst", "pain", "heartbreak",
 "unemployment", "sorrow", "unhappy", "painful", "crimes", "corruption",
 "hated", "hurts", "pollution", "agony", "drowned", "homeless", "robbed",
 "tsunami", "divorce", "depressed", "hurt", "cried", "crime", "loser", "hatred",
 "weep", "holocaust", "suffering", "injured", "hell", "suffered", "bombing",
 "devil", "horrible", "destruction", "cheating", "disappointed", "heartache",
 "sadly", "thieves", "theft", "fired", "fraud", "anger", "victims", "nightmare",
 "accident", "angry", "fear", "poor", "grief", "frustration", "tragic", "hate",
 "threat", "hurting", "graveside", "victim", "sad", "weapons", "asshole", "flu",
 "nigger", "slaughter", "wounded", "arrest", "negative", "flood", "worried",
 "attack", "killer", "ill", "enemies", "prisoners", "burial", "drowning",
 "saddened", "cheat", "hating", "dangerous", "stealing", "losses", "crashed",
 "attacks", "steal", "panic", "tears", "damaged", "saddam", "haters",
 "recession", "slap", "crisis", "betray", "psycho", "stolen", "shot", "shit",
 "motherfuckers", "attacked", "failing", "destroy", "bastard", "useless",
 "shooting", "tumor", "abandoned", "denied", "harm", "cocaine", "miserable",
 "ruined", "hurricane", "pissed", "broke", "corpse", "grave", "nightmares",
 "hopeless", "satan", "assault", "beating", "rage", "loss", "upset", "betrayed",
 "stroke"]

ANGRY_WORDS = ["rage", "enraged", "war", "murderer", "mutilate", "nightmare",
 "stress", "hate", "terrified", "shark", "mad", "danger", "assault", "betray",
 "gun", "killer", "crash", "revolt", "slaughter", "fight", "scalding", "scared",
 "cancer", "hostile", "terrorist", "anger", "snake", "bees", "obsession", "fear",
 "bomb", "anxious", "drown", "scream", "abuse", "rejected", "hurricane", "afraid",
 "angry", "alert", "whore", "evil", "outrage", "annoy", "fire", "rifle", "hatred",
 "volcano", "intruder", "distressed", "tease", "rude", "burn", "overwhelmed",
 "bastard", "humiliate", "storm", "sinful", "ulcer", "violent", "tornado", "bloody",
 "chaos", "destroy", "slap", "hurt", "thief", "guillotine", "vampire", "razor",
 "pervert", "pistol", "cyclone", "destruction", "aggressive", "riot", "noisy",
 "pollute", "trauma", "shotgun", "vomit", "quarrel", "rabies", "victim", "starving",
 "suspicious", "tense", "beast", "weapon", "hooker", "vandal", "accident",
 "gangrene", "demon", "leprosy", "toxic", "prison", "muscular", "trouble", "flood",
 "embattled", "lost", "despise", "ambition", "lion", "knife", "toothache",
 "disloyal", "punishment", "crucify", "wounds", "detest", "mountain", "mangle",
 "alien", "lesbian", "snob", "child", "mischief", "fragrance", "offend",
 "regretful", "crushed", "assassin", "disturb", "voyage", "bankrupt", "dreadful",
 "pain", "robber", "spanking", "insolent", "surgery", "tumor", "insane", "brutal",
 "wife", "addict", "deceit", "chance", "obscene", "dentist", "despairing",
 "skyscraper", "jewel", "body", "controlling", "event", "legend", "idea", "injury",
 "python", "pressure", "jealousy", "frustrated", "confused", "wicked", "nervous",
 "execution", "terrible", "scorn", "doctor", "hostage", "fearful", "venom",
 "massacre", "grenade", "spider", "unfaithful", "dagger", "agony", "putrid",
 "burdened", "bottle", "bullet", "hard", "priest", "traitor", "invest", "dead",
 "wasp", "cold", "skull", "flag", "hit", "broken", "upset", "greed", "song",
 "insult", "rancid", "alcoholic", "time", "skeptical", "mighty", "lie", "employment",
 "selfish", "cockroach", "pest", "angry", "affronted", "annoyed", "antagonized", "bitter",
    "chafed", "choleric", "convulsed", "cross", "displeased", "enraged",
    "exacerbated", "exasperated", "ferocious", "fierce", "fiery", "fuming",
    "furious", "galled", "hateful", "heated", "hot", "huffy", "impassioned",
    "incensed", "indignant", "inflamed", "infuriated", "irascible", "irate",
    "ireful", "irritable", "irritated", "maddened", "nettled", "offended",
    "outraged", "piqued", "provoked", "raging", "resentful", "riled", "sore",
    "splenetic", "storming", "sulky", "sullen", "turbulent", "uptight",
    "vexed", "wrathful"]